export const SPRITE_SHEET = {
    WIDTH : 16,
    HEIGHT: 16.4,
    BORDER: 0,
    SPACING: 0,
    CHARACTER_SECTION_Y_OFFSET: 383.7,
    CHARACTER_SECTION_X_OFFSET: 64
}
export const SCALE_FACTOR = 4;