import { PreviewObjectItem } from "../types/general";
import { CustomPlacementType } from "../types/placement";

export const previewObjectList: { [key in CustomPlacementType]: PreviewObjectItem[] } = {
    Character: [
        {
            id: "main character",
            type: "Character",
            objectItemName: "main character",
            avatar: "",
        },
    ],
    Enemy: [],
    PickUp: [
        {
            id: "resume",
            type: "PickUp",
            objectItemName: "resume",
            avatar: "",
        },
    ],
    Tile: [
        {
            id: "balloon",
            type: "Tile",
            objectItemName: "balloon",
            avatar: "",
        },
        {
            id: "flowers",
            type: "Tile",
            objectItemName: "flowers",
            avatar: "",
        },
        {
            id: "shrub",
            type: "Tile",
            objectItemName: "shrub",
            avatar: "",
        },
        {
            id: "signage-intro",
            type: "Tile",
            objectItemName: "signage",
            avatar: "",
            signageType: "intro",
        },
        {
            id: "signage-skill",
            type: "Tile",
            objectItemName: "signage",
            avatar: "",
            signageType: "skill",
        },
        {
            id: "signage-project",
            type: "Tile",
            objectItemName: "signage",
            avatar: "",
            signageType: "project",
        },
        {
            id: "signage-education",
            type: "Tile",
            objectItemName: "signage",
            avatar: "",
            signageType: "education",
        },
        {
            id: "signage-experience",
            type: "Tile",
            objectItemName: "signage",
            avatar: "",
            signageType: "experience",
        },
        {
            id: "signage2-skill-languages",
            type: "Tile",
            objectItemName: "signage2",
            avatar: "",
            signageType: "skill-languages",
        },
        {
            id: "signage2-skill-frontend",
            type: "Tile",
            objectItemName: "signage2",
            avatar: "",
            signageType: "skill-frontend",
        },
        {
            id: "signage2-skill-backend",
            type: "Tile",
            objectItemName: "signage2",
            avatar: "",
            signageType: "skill-backend",
        },
        {
            id: "signage2-skill-others",
            type: "Tile",
            objectItemName: "signage2",
            avatar: "",
            signageType: "skill-others",
        },
        {
            id: "finish-line",
            type: "Tile",
            objectItemName: "finish line",
            avatar: "",
        },
        {
            id: "portal-prev",
            type: "Tile",
            objectItemName: "portal",
            avatar: "",
            portalType: "prev",
        },
        {
            id: "portal-next",
            type: "Tile",
            objectItemName: "portal",
            avatar: "",
            portalType: "next",
        },
        {
            id: "company-pl",
            type: "Tile",
            objectItemName: "company",
            avatar: "",
            companyType: "pl",
        },
        {
            id: "company-yau-lee",
            type: "Tile",
            objectItemName: "company",
            avatar: "",
            companyType: "yau-lee",
        },
        {
            id: "company-redcliff",
            type: "Tile",
            objectItemName: "company",
            avatar: "",
            companyType: "redcliff",
        },
        {
            id: "painting-project-gamehub",
            type: "Tile",
            objectItemName: "painting",
            avatar: "",
            paintingType: "project-gamehub",
        },
        {
            id: "painting-project-big-two",
            type: "Tile",
            objectItemName: "painting",
            avatar: "",
            paintingType: "project-big-two",
        },
        {
            id: "painting-project-character-gpt",
            type: "Tile",
            objectItemName: "painting",
            avatar: "",
            paintingType: "project-character-gpt",
        },
        {
            id: "painting-project-sudoku",
            type: "Tile",
            objectItemName: "painting",
            avatar: "",
            paintingType: "project-sudoku",
        },
        {
            id: "painting-project-final-year-project",
            type: "Tile",
            objectItemName: "painting",
            avatar: "",
            paintingType: "project-final-year-project",
        },
        {
            id: "painting-project-arduino-car",
            type: "Tile",
            objectItemName: "painting",
            avatar: "",
            paintingType: "project-arduino-car",
        },
        {
            id: "painting-project-portfolio-game-v1",
            type: "Tile",
            objectItemName: "painting",
            avatar: "",
            paintingType: "project-portfolio-game-v1",
        },
    ],
};
